package rules

import com.diagnosis.sbnz.model.Patient
import com.diagnosis.sbnz.model.Illness
import com.diagnosis.sbnz.model.enums.SymptomType
import com.diagnosis.sbnz.model.enums.IllnessType

rule "Flu phase 1"
	when 
		patient : Patient()
		eval( patient.getIllness().getIllnessType() == IllnessType.Flu && patient.getIllness().getIllnessPhase() == 1)
	then
		patient.addSymptom(SymptomType.RunyNose);
	end
	
rule "Flu phase 2"
	when 
		patient : Patient()
		eval( patient.getIllness().getIllnessType() == IllnessType.Flu && patient.getIllness().getIllnessPhase() == 2)
	then
		patient.addSymptom(SymptomType.Caughing);
	end
	
rule "Flu phase 4"
	when 
		patient : Patient()
		eval( patient.getIllness().getIllnessType() == IllnessType.Flu && patient.getIllness().getIllnessPhase() == 4)
	then
		patient.addSymptom(SymptomType.Fever);
	end
		
